### ISSUE TITLE
Null pointer error while launching

### ISSUE THREAD

**Issue by banerjed** [fullstackreact/FirestackApp#13]
This is such a fantastic idea and has the exact features I was trying to put together for (Firebase backend, chat integration, Auth0 for authentication, NativeBase for look-and-feel) - thanks for putting this together. While I haven't been able to run it, it seems to have a lot of built-in functionality.

Seeing the following error while running. Steps I followed:
>>  git clone ...; npm install; react-native run-ios

Running on MacOS Sierra 10.12.2

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at launchEditor (/Users/banerjed/projects/FirestackApp/node_modules/react-native/local-cli/server/util/launchEditor.js:153:29)
    at Object.handle (/Users/banerjed/projects/FirestackApp/node_modules/react-native/local-cli/server/middleware/openStackFrameInEditorMiddleware.js:17:7)
    at next (/Users/banerjed/projects/FirestackApp/node_modules/connect/lib/proto.js:174:15)
    at Object.handle (/Users/banerjed/projects/FirestackApp/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:89:7)
    at next (/Users/banerjed/projects/FirestackApp/node_modules/connect/lib/proto.js:174:15)
    at Object.handle (/Users/banerjed/projects/FirestackApp/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:89:7)
    at next (/Users/banerjed/projects/FirestackApp/node_modules/connect/lib/proto.js:174:15)
    at Object.compression [as handle] (/Users/banerjed/projects/FirestackApp/node_modules/compression/index.js:205:5)
    at next (/Users/banerjed/projects/FirestackApp/node_modules/connect/lib/proto.js:174:15)
    at IncomingMessage.<anonymous> (/Users/banerjed/projects/FirestackApp/node_modules/react-native/local-cli/server/middleware/loadRawBodyMiddleware.js:20:5)

**Comment by banerjed** [comment]
Traced it down to not having done the native linking process outlined in https://github.com/fullstackreact/react-native-firestack

The following steps needed to be performed:
react-native link react-native-firestack; pod update --verbose

At this stage, pod update failed for me with the following error:
The dependency `Firebase` is not used in any concrete target.
The dependency `Firebase/Core` is not used in any concrete target.
....
The dependency `Firebase/Messaging` is not used in any concrete target.

To get around that, I had to upgrade my Podfile to look as follows:

Dhritimans-iMac:FirestackApp banerjed$ cat ios/Podfile
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirestackApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for FirestackApp
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'

  target 'FirestackAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

This allowed the app to launch - however, I also needed to do the following step, since it complained about missing 'Ionicons'

>> react-native link react-native-vector-icons

**Comment by banerjed** [comment]
The podfile got messed up in the previous update. Repasting below to make it look nicer. 

To summarize, the following steps helped me get started:

1. Change ios/Podfile as below
2. Run the following 2 commands:
  >> react-native link react-native-firestack; pod update --verbose
  >> react-native link react-native-vector-icons

The updated ios/Podfile is:

target 'FirestackApp' do
  use_frameworks!

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'

  target 'FirestackAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
